"""Ajout module galerie

Revision ID: b674e149a426
Revises: 016c6d354435
Create Date: 2026-09-04 02:20:01.724647

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b674e149a426'
down_revision: Union[str, Sequence[str], None] = '016c6d354435'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reunions')
    op.drop_table('khassida_tons')
    op.drop_index(op.f('idx_communications_actif'), table_name='communications')
    op.drop_index(op.f('idx_communications_date_publication'), table_name='communications')
    op.drop_index(op.f('idx_communications_priorite'), table_name='communications')
    op.drop_index(op.f('idx_communications_type'), table_name='communications')
    op.drop_table('communications')
    op.drop_table('programmes')
    op.drop_index(op.f('ix_notifications_created_at'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_lu'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_utilisateur_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('idx_audios_khassida_id'), table_name='audios')
    op.alter_column('declamation_khassidas', 'ton_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('depenses', 'motif',
               existing_type=sa.VARCHAR(length=150),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('paiements', 'cotisation_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('permissions', 'description',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True)
    op.drop_constraint(op.f('permissions_code_key'), 'permissions', type_='unique')
    op.create_index(op.f('ix_permissions_code'), 'permissions', ['code'], unique=True)
    op.drop_constraint(op.f('repetition_khassidas_unique'), 'repetition_khassidas', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('repetition_khassidas_unique'), 'repetition_khassidas', ['repetition_id', 'khassida_id'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_permissions_code'), table_name='permissions')
    op.create_unique_constraint(op.f('permissions_code_key'), 'permissions', ['code'], postgresql_nulls_not_distinct=False)
    op.alter_column('permissions', 'description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('paiements', 'cotisation_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('depenses', 'motif',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=150),
               existing_nullable=False)
    op.alter_column('declamation_khassidas', 'ton_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.create_index(op.f('idx_audios_khassida_id'), 'audios', ['khassida_id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('utilisateur_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('titre', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('message', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('type', sa.VARCHAR(length=50), server_default=sa.text("'INFO'::character varying"), autoincrement=False, nullable=False),
    sa.Column('route', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('lu', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('date_lecture', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['utilisateur_id'], ['utilisateurs.id'], name=op.f('notifications_utilisateur_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('notifications_pkey'))
    )
    op.create_index(op.f('ix_notifications_utilisateur_id'), 'notifications', ['utilisateur_id'], unique=False)
    op.create_index(op.f('ix_notifications_lu'), 'notifications', ['lu'], unique=False)
    op.create_index(op.f('ix_notifications_created_at'), 'notifications', ['created_at'], unique=False)
    op.create_table('programmes',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('titre', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('date_debut', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('date_fin', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('lieu', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('actif', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('programmes_pkey'))
    )
    op.create_table('communications',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('titre', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('contenu', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('type_communication', sa.VARCHAR(length=50), server_default=sa.text("'ANNONCE'::character varying"), autoincrement=False, nullable=False),
    sa.Column('priorite', sa.VARCHAR(length=30), server_default=sa.text("'NORMALE'::character varying"), autoincrement=False, nullable=False),
    sa.Column('date_publication', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('date_expiration', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('actif', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('communications_pkey'))
    )
    op.create_index(op.f('idx_communications_type'), 'communications', ['type_communication'], unique=False)
    op.create_index(op.f('idx_communications_priorite'), 'communications', ['priorite'], unique=False)
    op.create_index(op.f('idx_communications_date_publication'), 'communications', ['date_publication'], unique=False)
    op.create_index(op.f('idx_communications_actif'), 'communications', ['actif'], unique=False)
    op.create_table('khassida_tons',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('khassida_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('ton_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['khassida_id'], ['khassidas.id'], name=op.f('khassida_tons_khassida_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ton_id'], ['tons.id'], name=op.f('khassida_tons_ton_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('khassida_tons_pkey'))
    )
    op.create_table('reunions',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('titre', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('date_reunion', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('lieu', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('actif', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('type_reunion', sa.VARCHAR(length=30), server_default=sa.text("'MENSUELLE'::character varying"), autoincrement=False, nullable=False),
    sa.Column('ordre_du_jour', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('statut', sa.VARCHAR(length=30), server_default=sa.text("'PROGRAMMEE'::character varying"), autoincrement=False, nullable=False),
    sa.Column('compte_rendu', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('adresse', sa.VARCHAR(length=300), autoincrement=False, nullable=True),
    sa.Column('latitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('longitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('reunions_pkey'))
    )
    # ### end Alembic commands ###
