"""ajouter table membre fonctions

Revision ID: d55430854096
Revises: b674e149a426
Create Date: 2026-09-04 04:53:29.723525

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd55430854096'
down_revision: Union[str, Sequence[str], None] = 'b674e149a426'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('membre_fonctions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('membre_id', sa.BigInteger(), nullable=False),
    sa.Column('fonction_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['fonction_id'], ['fonctions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['membre_id'], ['membres.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('membre_id', 'fonction_id', name='uq_membre_fonction')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('membre_fonctions')
    # ### end Alembic commands ###
