"""baseline schema complet

Revision ID: 027717562ea8
Revises: d55430854096
Create Date: 2026-09-04 05:17:17.065076

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '027717562ea8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aides_exterieures',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('source', sa.String(length=150), nullable=False),
    sa.Column('montant', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('date_aide', sa.Date(), nullable=False),
    sa.Column('actif', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('communications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titre', sa.String(length=200), nullable=False),
    sa.Column('contenu', sa.Text(), nullable=False),
    sa.Column('type_communication', sa.String(length=50), nullable=False),
    sa.Column('priorite', sa.String(length=30), nullable=False),
    sa.Column('date_publication', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('date_expiration', sa.DateTime(), nullable=True),
    sa.Column('actif', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_communications_id'), 'communications', ['id'], unique=False)
    op.create_table('depenses',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('motif', sa.String(length=255), nullable=False),
    sa.Column('type_sortie', sa.String(length=50), server_default='AUTRE', nullable=False),
    sa.Column('remis_a', sa.String(length=255), nullable=False),
    sa.Column('montant', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('date_depense', sa.Date(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('piece_jointe_nom', sa.String(length=255), nullable=True),
    sa.Column('piece_jointe_path', sa.String(length=500), nullable=True),
    sa.Column('actif', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fonctions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('actif', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nom')
    )
    op.create_table('galeries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titre', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('type_media', sa.String(length=20), nullable=False),
    sa.Column('nom_fichier', sa.String(length=255), nullable=False),
    sa.Column('chemin_fichier', sa.String(length=500), nullable=False),
    sa.Column('ordre', sa.Integer(), nullable=False),
    sa.Column('actif', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_galeries_id'), 'galeries', ['id'], unique=False)
    op.create_table('khassidas',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('titre', sa.String(length=200), nullable=False),
    sa.Column('auteur', sa.String(length=150), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('actif', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('membres',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.Column('prenom', sa.String(length=100), nullable=False),
    sa.Column('telephone', sa.String(length=30), nullable=False),
    sa.Column('lieu_residence', sa.String(length=150), nullable=False),
    sa.Column('montant_cotisation', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('actif', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('telephone')
    )
    op.create_table('permissions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('nom', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('actif', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_permissions_code'), 'permissions', ['code'], unique=True)
    op.create_table('reunions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titre', sa.String(length=150), nullable=False),
    sa.Column('type_reunion', sa.String(length=30), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('ordre_du_jour', sa.Text(), nullable=True),
    sa.Column('date_reunion', sa.DateTime(), nullable=False),
    sa.Column('lieu', sa.String(length=200), nullable=False),
    sa.Column('adresse', sa.String(length=300), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('statut', sa.String(length=30), nullable=False),
    sa.Column('compte_rendu', sa.Text(), nullable=True),
    sa.Column('actif', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reunions_id'), 'reunions', ['id'], unique=False)
    op.create_table('tons',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('nom', sa.String(length=150), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('actif', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nom')
    )
    op.create_table('audios',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('khassida_id', sa.BigInteger(), nullable=False),
    sa.Column('ton_id', sa.BigInteger(), nullable=False),
    sa.Column('titre', sa.String(length=200), nullable=False),
    sa.Column('fichier', sa.String(length=500), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('actif', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['khassida_id'], ['khassidas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ton_id'], ['tons.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cotisations',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('membre_id', sa.BigInteger(), nullable=False),
    sa.Column('montant', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('montant_du', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('mois_concerne', sa.String(length=20), nullable=False),
    sa.Column('annee', sa.Integer(), nullable=False),
    sa.Column('date_cotisation', sa.Date(), nullable=False),
    sa.Column('actif', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['membre_id'], ['membres.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fonction_permissions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('fonction_id', sa.BigInteger(), nullable=False),
    sa.Column('permission_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['fonction_id'], ['fonctions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fonction_id', 'permission_id', name='uq_fonction_permission')
    )
    op.create_table('khassida_tons',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('khassida_id', sa.BigInteger(), nullable=False),
    sa.Column('ton_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['khassida_id'], ['khassidas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ton_id'], ['tons.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('kourels',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('nom', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('actif', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('gestionnaire_membre_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['gestionnaire_membre_id'], ['membres.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nom')
    )
    op.create_table('membre_fonctions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('membre_id', sa.BigInteger(), nullable=False),
    sa.Column('fonction_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['fonction_id'], ['fonctions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['membre_id'], ['membres.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('membre_id', 'fonction_id', name='uq_membre_fonction')
    )
    op.create_table('utilisateurs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('membre_id', sa.BigInteger(), nullable=False),
    sa.Column('identifiant', sa.String(length=100), nullable=False),
    sa.Column('mot_de_passe_hash', sa.Text(), nullable=False),
    sa.Column('premiere_connexion', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('actif', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('dernier_acces', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['membre_id'], ['membres.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('identifiant'),
    sa.UniqueConstraint('membre_id')
    )
    op.create_table('kourel_membres',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('kourel_id', sa.BigInteger(), nullable=False),
    sa.Column('membre_id', sa.BigInteger(), nullable=False),
    sa.Column('date_entree', sa.Date(), nullable=False),
    sa.Column('date_sortie', sa.Date(), nullable=True),
    sa.Column('gestionnaire', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('actif', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['kourel_id'], ['kourels.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['membre_id'], ['membres.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kourel_id', 'membre_id', name='uq_kourel_membre')
    )
    op.create_table('notifications',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('utilisateur_id', sa.BigInteger(), nullable=False),
    sa.Column('titre', sa.String(length=200), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('type', sa.String(length=50), server_default='INFO', nullable=False),
    sa.Column('route', sa.String(length=255), nullable=True),
    sa.Column('lu', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('date_lecture', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['utilisateur_id'], ['utilisateurs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_created_at'), 'notifications', ['created_at'], unique=False)
    op.create_index(op.f('ix_notifications_lu'), 'notifications', ['lu'], unique=False)
    op.create_index(op.f('ix_notifications_utilisateur_id'), 'notifications', ['utilisateur_id'], unique=False)
    op.create_table('paiements',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('membre_id', sa.BigInteger(), nullable=False),
    sa.Column('cotisation_id', sa.BigInteger(), nullable=False),
    sa.Column('montant', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('mode_paiement', sa.String(length=50), nullable=False),
    sa.Column('date_paiement', sa.Date(), nullable=False),
    sa.Column('reference', sa.String(length=100), nullable=True),
    sa.Column('actif', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cotisation_id'], ['cotisations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['membre_id'], ['membres.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('programmes_mensuels',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('kourel_id', sa.BigInteger(), nullable=False),
    sa.Column('annee', sa.Integer(), nullable=False),
    sa.Column('mois', sa.Integer(), nullable=False),
    sa.Column('date_debut', sa.Date(), nullable=False),
    sa.Column('date_fin', sa.Date(), nullable=False),
    sa.Column('actif', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['kourel_id'], ['kourels.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('utilisateur_fonctions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('utilisateur_id', sa.BigInteger(), nullable=False),
    sa.Column('fonction_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['fonction_id'], ['fonctions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['utilisateur_id'], ['utilisateurs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('utilisateur_id', 'fonction_id', name='uq_utilisateur_fonction')
    )
    op.create_table('declamations',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('programme_id', sa.BigInteger(), nullable=False),
    sa.Column('date_declamation', sa.Date(), nullable=False),
    sa.Column('heure', sa.Time(), nullable=True),
    sa.Column('lieu', sa.String(length=200), nullable=True),
    sa.Column('evenement', sa.String(length=200), nullable=False),
    sa.Column('khassida_id', sa.BigInteger(), nullable=True),
    sa.Column('actif', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['khassida_id'], ['khassidas.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['programme_id'], ['programmes_mensuels.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('repetitions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('programme_id', sa.BigInteger(), nullable=False),
    sa.Column('date_repetition', sa.Date(), nullable=False),
    sa.Column('heure_debut', sa.Time(), nullable=True),
    sa.Column('heure_fin', sa.Time(), nullable=True),
    sa.Column('lieu', sa.String(length=200), nullable=True),
    sa.Column('actif', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['programme_id'], ['programmes_mensuels.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('declamation_khassidas',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('declamation_id', sa.BigInteger(), nullable=False),
    sa.Column('khassida_id', sa.BigInteger(), nullable=False),
    sa.Column('ton_id', sa.BigInteger(), nullable=False),
    sa.Column('ordre', sa.Integer(), server_default='1', nullable=False),
    sa.ForeignKeyConstraint(['declamation_id'], ['declamations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['khassida_id'], ['khassidas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ton_id'], ['tons.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('repetition_khassidas',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('repetition_id', sa.BigInteger(), nullable=False),
    sa.Column('khassida_id', sa.BigInteger(), nullable=False),
    sa.Column('audio_id', sa.BigInteger(), nullable=False),
    sa.Column('ordre', sa.Integer(), server_default='1', nullable=False),
    sa.Column('actif', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['audio_id'], ['audios.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['khassida_id'], ['khassidas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['repetition_id'], ['repetitions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('repetition_khassidas')
    op.drop_table('declamation_khassidas')
    op.drop_table('repetitions')
    op.drop_table('declamations')
    op.drop_table('utilisateur_fonctions')
    op.drop_table('programmes_mensuels')
    op.drop_table('paiements')
    op.drop_index(op.f('ix_notifications_utilisateur_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_lu'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_created_at'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_table('kourel_membres')
    op.drop_table('utilisateurs')
    op.drop_table('membre_fonctions')
    op.drop_table('kourels')
    op.drop_table('khassida_tons')
    op.drop_table('fonction_permissions')
    op.drop_table('cotisations')
    op.drop_table('audios')
    op.drop_table('tons')
    op.drop_index(op.f('ix_reunions_id'), table_name='reunions')
    op.drop_table('reunions')
    op.drop_index(op.f('ix_permissions_code'), table_name='permissions')
    op.drop_table('permissions')
    op.drop_table('membres')
    op.drop_table('khassidas')
    op.drop_index(op.f('ix_galeries_id'), table_name='galeries')
    op.drop_table('galeries')
    op.drop_table('fonctions')
    op.drop_table('depenses')
    op.drop_index(op.f('ix_communications_id'), table_name='communications')
    op.drop_table('communications')
    op.drop_table('aides_exterieures')
    # ### end Alembic commands ###
